---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: getourneau/buildpacks-light
inputs:
  - name: buildpack-master
  - name: buildpack-packager
  - name: buildpacks-ci
outputs:
  - name: buildpack-artifacts
run:
  path: buildpacks-ci/scripta/package-buildpack.sh
