resources:
  - name: oracle-tar
    type: s3
    source:
      bucket: {{buildpacks-binaries-s3-bucket}}
      regexp: instantclient-gwenn.x64-(.*).tar.gz
      access_key_id: {{access-key-concourse-bucket}}
      secret_access_key: {{secret-key-concourse-bucket}}
      region_name: {{buildpack-s3-region}}
  # - name: php-buildpack-cached
  #   type: s3
  #   source:
  #     bucket: {{buildpacks-binaries-s3-bucket}}
  #     access_key_id: {{access-key-concourse-bucket}}
  #     secret_access_key: {{secret-key-concourse-bucket}}
  #     region_name: {{buildpack-s3-region}}
  - name: binary-builder-fork
    type: git
    source:
      uri: {{binary-builder-git-uri-fork}}
      branch: fork-yahoo
      private_key: {{private-key-github-concourse}}
  - name: binary-builder-official
    type: git
    source:
      uri: {{binary-builder-git-uri}}
      private_key: {{private-key-github-concourse}}
  - name: buildpacks-ci
    type: git
    source:
      uri: {{buildpacks-ci-git-uri-public}}
      branch: {{buildpacks-ci-git-uri-public-branch}}
  - name: builds-out
    type: git
    source:
      branch: binary-builds
      private_key: {{private-key-github-concourse}}
      uri: {{buildpacks-ci-git-uri}}

  # - name: build-tar
  #   type: s3
  #   source:
  #     bucket: {{buildpacks-binaries-s3-bucket}}
  #     versioned_file: /concourse-artifacts/binary-builder-source.tgz
  #     access_key_id: {{access-key-concourse-bucket}}
  #     secret_access_key: {{secret-key-concourse-bucket}}
  #     region_name: {{buildpack-s3-region}}

  - name: php-builds
    type: git
    source:
      branch: binary-builds
      private_key: {{private-key-github-concourse}}
      uri: {{buildpacks-ci-git-uri}}
      paths: [ php-builds.yml ]

  - name: php-built-output
    type: git
    source:
      branch: binary-built-output
      private_key: {{private-key-github-concourse}}
      uri: {{buildpacks-ci-git-uri}}
      paths: [ php-built.yml ]

  - name: php7-builds
    type: git
    source:
      branch: binary-builds
      private_key: {{private-key-github-concourse}}
      uri: {{buildpacks-ci-git-uri}}
      paths: [ php7-builds.yml ]

  - name: php7-built-output
    type: git
    source:
      branch: binary-built-output
      private_key: {{private-key-github-concourse}}
      uri: {{buildpacks-ci-git-uri}}
      paths: [ php7-built.yml ]

  - name: php-buildpack-official
    type: git
    source:
      uri: git@github.com:cloudfoundry/php-buildpack.git
      private_key: {{private-key-github-concourse}}
      branch: master
      ignore_paths:
        - VERSION
        - CHANGELOG

  - name: php-buildpack-yahoo-fork
    type: git
    source:
      uri: git@github.com:shinji62/php-buildpack.git
      private_key: {{private-key-github-concourse}}
      branch: yahoo-fork
      ignore_paths:
        - VERSION
        - CHANGELOG



jobs:
- name: merge-upstream-to-fork-php-buildpack
  public: true
  serial: true
  plan:
  - aggregate:
    - get: buildpacks-ci
    - get: release-repo-fork
      resource: php-buildpack-yahoo-fork 
      trigger: true
    - get: release-repo-upstream
      resource: php-buildpack-official
      trigger: true
  - task: merge-upstream-to-fork-branch
    file: buildpacks-ci/tasks/merge-upstream-to-fork.yml
    params:
      GIT_USERNAME: {{github-username}}
      GIT_EMAIL:  {{github-email}}
  - put: php-buildpack-yahoo-fork
    params:
      repository: merged-repo


- name: merge-upstream-to-fork-binary-builder
  public: true
  serial: true
  plan:
  - aggregate:
    - get: buildpacks-ci
    - get: release-repo-fork
      resource: binary-builder-fork
      trigger: true
    - get: release-repo-upstream
      resource: binary-builder-official
      trigger: true
  - task: merge-upstream-to-fork-branch
    file: buildpacks-ci/tasks/merge-upstream-to-fork.yml
    params:
      GIT_USERNAME: {{github-username}}
      GIT_EMAIL:  {{github-email}}
  - put: binary-builder-fork
    params:
      repository: merged-repo



- name: check-binary-to-build
  serial: true
  public: true
  plan:
    - aggregate:
       - get: builds-yaml
         resource: builds-out
       - get: buildpack
         resource: php-buildpack-yahoo-fork
         trigger: true
         passed: [merge-upstream-to-fork-php-buildpack]
       - get: buildpacks-ci
    - do:
      - task: update-manifest
        file: buildpacks-ci/tasks/update-manifest.yml
        params:
          AWS_DEFAULT_REGION: ap-northeast-1
          AWS_ACCESS_KEY_ID: {{access-key-concourse-bucket}}
          AWS_SECRET_ACCESS_KEY: {{secret-key-concourse-bucket}}
          BP_BINARIES: buildpacks-binaries-bucket
      - task: generate-builds
        file: buildpacks-ci/tasks/generate-builds.yml
        params:
          BINARY: php
      - put: builds-out
        params: 
          repository: builds-yaml-output
          rebase: true



- name: build-php
  serial: true
  public: true
  disable_manual_trigger: true
  serial_groups: [building-php]
  plan:
    - aggregate:
      - get: builds-out
        passed: [check-binary-to-build]
      - get: builds-yaml
        resource: php-builds
        trigger: true
      - get: binary-builder
        resource: binary-builder-fork
      - get: oracle-tar
      - get: buildpacks-ci
      - get: built-yaml
        resource: php-built-output
    - do:
      - task: build-binary
        file: buildpacks-ci/tasks/build-binary.yml
        params:
          BINARY_NAME: php
          GIT_SSH_KEY: {{private-key-github-concourse}}
          RUBYGEM_MIRROR: {{rubygem-mirror}}
          BINARY_BUILDER_PLATFORM: {{binary-builder-platform}}
          BINARY_BUILDER_OS_NAME: {{binary-builder-os-name}}
        privileged: true
      - task: push-binary
        file: buildpacks-ci/tasks/push-binary.yml
        params:
          BINARY_NAME: php
          BUCKET_NAME: {{buildpacks-binaries-s3-bucket}}
          AWS_ACCESS_KEY_ID: {{access-key-concourse-bucket}}
          AWS_SECRET_ACCESS_KEY: {{secret-key-concourse-bucket}}
          AWS_DEFAULT_REGION: ap-northeast-1
        privileged: true
      - put: builds-out
        params:
          repository: builds-yaml-artifacts
          rebase: true



- name: build-php7
  serial: true
  public: true
  disable_manual_trigger: true
  serial_groups: [building-php]
  plan:
    - aggregate:
      - get: builds-out
        passed: [check-binary-to-build]
      - get: builds-yaml
        resource: php7-builds
        trigger: true
      - get: binary-builder
        resource: binary-builder-fork
      - get: oracle-tar
      - get: buildpacks-ci
      - get: built-yaml
        resource: php7-built-output
    - do:
      - task: build-binary
        file: buildpacks-ci/tasks/build-binary.yml
        params:
          BINARY_NAME: php7
          GIT_SSH_KEY: {{private-key-github-concourse}}
          RUBYGEM_MIRROR: {{rubygem-mirror}}
          BINARY_BUILDER_PLATFORM: {{binary-builder-platform}}
          BINARY_BUILDER_OS_NAME: {{binary-builder-os-name}}
        privileged: true
      - task: push-binary
        file: buildpacks-ci/tasks/push-binary.yml
        params:
          BINARY_NAME: php7
          BUCKET_NAME: {{buildpacks-binaries-s3-bucket}}
          AWS_ACCESS_KEY_ID: {{access-key-concourse-bucket}}
          AWS_SECRET_ACCESS_KEY: {{secret-key-concourse-bucket}}
          AWS_DEFAULT_REGION: ap-northeast-1
        privileged: true
      - put: builds-out
        params:
          repository: builds-yaml-artifacts
          force: true


# - name: update-manifest-php
#   public: true
#   serial: true
#   plan:
#   - aggregate: 
#     - get: builds-yaml
#       resource: php-builds
#       passed: [build-php]
#     - get: buildpacks-ci
#     - get: buildpack
#       resource: php-buildpack-yahoo-fork
#   - task: update-manifest
#     file: buildpacks-ci/tasks/update-manifest.yml
#     params:
#       AWS_DEFAULT_REGION: ap-northeast-1
#       AWS_ACCESS_KEY_ID: {{access-key-concourse-bucket}}
#       AWS_SECRET_ACCESS_KEY: {{secret-key-concourse-bucket}}
#       BP_BINARIES: buildpacks-binaries-bucket
#   - put: php-buildpack-yahoo-fork
#     params:
#       repository: buildpack-updated-repos
#       rebase: true


# - name: update-manifest-php7
#   public: true
#   serial: true
#   plan:
#   - aggregate: 
#     - get: builds-yaml
#       resource: php7-builds
#       passed: [build-php7]
#     - get: buildpacks-ci
#     - get: buildpack
#       resource: php-buildpack-yahoo-fork
#   - task: update-manifest
#     file: buildpacks-ci/tasks/update-manifest.yml
#     params:
#       AWS_DEFAULT_REGION: ap-northeast-1
#       AWS_ACCESS_KEY_ID: {{access-key-concourse-bucket}}
#       AWS_SECRET_ACCESS_KEY: {{secret-key-concourse-bucket}}
#       BP_BINARIES: buildpacks-binaries-bucket
#   - put: php-buildpack-yahoo-fork
#     params:
#       repository: buildpack-updated-repos
#       rebase: true

# - name: generate-php-buildpack
#   public: true
#   serial: true
#   plan:
#   - aggregate:
#     - get: buildpacks-ci
#     - get: buildpack
#       resource: php-buildpack-yahoo-fork
#       passed: [merge-upstream-to-fork-php-buildpack,update-manifest]


#   - task: update-manifest
#     file: buildpacks-ci/tasks/update-manifest.yml
#     params:
#       AWS_DEFAULT_REGION: ap-northeast-1
#       AWS_ACCESS_KEY_ID: {{access-key-concourse-bucket}}
#       AWS_SECRET_ACCESS_KEY: {{secret-key-concourse-bucket}}
#       BP_BINARIES: buildpacks-binaries-bucket


#   - task: generate-builpack
#     file: buildpacks-ci/tasks/detect-and-upload.yml
#     params:
#       RUBYGEM_MIRROR: {{rubygem-mirror}}
#   - task: upload-buildpack 






# - name: test-php7
#   serial: true
#   public: true
#   plan:
#     - aggregate:
#       - get: build-tar
#         passed: [ build-php7 ]
#         trigger: true
#       - get: buildpacks-ci
#     - task: run tests
#       file: buildpacks-ci/tasks/run-unit-tests-for-php7.yml

