---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cflinuxfs2
inputs:
  - name: binary-builder
  - name: buildpacks-ci
  - name: builds-yaml
  - name: built-yaml
  - name: oracle-tar
outputs:
  - name: binary-builder-artifacts
  - name: builds-yaml-artifacts
run:
  path: bash
  args:
    - -cl
    - |
      tar xvf oracle-tar/instantclient-gwenn*.tar.gz
      mv  ./instantclient_12_1 /oracle
      buildpacks-ci/tasks/build-binary/run.sh
      
params:
  RUBYGEM_MIRROR:
