#!/bin/sh
set -e -x

GIT_EMAIL="${GIT_EMAIL:?"GIT_EMAIL required"}"
GIT_USERNAME="${GIT_USERNAME:?"GIT_USERNAME required"}"

UPSTREAM=$PWD/release-repo-upstream

git clone ./release-repo-fork ./merged-repo

cd merged-repo

git config user.name "${GIT_USERNAME}"
git config user.email "${GIT_EMAIL}"
git remote add upstream $UPSTREAM
git fetch upstream
git merge --no-edit upstream/master

git log -n 3 | cat